### ISSUE TITLE
Improve device connection indicator messages

### ISSUE THREAD

**Issue by oantila** [Andychochocho/android-testing-tool#12]
The "Device was unplugged" and "Device was plugged in" messages sound a little awkward. Let's change them to the following:

- Device not connected
- Device connected

Later once we have the device model identification working, it can change to "Device connected: [model]"

**Comment by Andychochocho** [comment]
Just updated the message, will add the model # later. Coming back to this later.

**Comment by oantila** [comment]
@Andychochocho instead of closing tickets after implementing the change, please move them to the Test column so I can verify in a build.

**Comment by Andychochocho** [comment]
@oantila Sounds good!
