### ISSUE TITLE
Update Github project description

### ISSUE THREAD

**Issue by oantila** [Andychochocho/android-testing-tool#15]
The current project description near the top of https://github.com/Andychochocho/android-testing-tool doesn't read well so let's update it. I'm not able to update it myself so creating this ticket.

Current: A testing tool designed for android devices meant for QA analysts and engineers.

Update to: A lightweight Android app testing tool for QA professionals.

**Comment by Andychochocho** [comment]
Just updated the project with this on commit 2c5b540.

**Comment by oantila** [comment]
Still seeing the old description.

**Comment by Andychochocho** [comment]
@oantila Oh, I thought you were referring to the project description in the app itself. I'll update this right now.
