### ISSUE TITLE
Save Logs button is functional even if device is not connected

### ISSUE THREAD

**Issue by oantila** [Andychochocho/android-testing-tool#6]
The Save Logs button is functional even if no device is detected. Button should be disabled if there's no connected device, or an error message should pop up saying "Please connect your device first" when button is clicked. Let's implement which ever is the easiest/fastest to do.

Steps to reproduce:
1. Install build: https://www.dropbox.com/s/1l1hxinlwni6xhn/Android%20Test%20Tool.zip?dl=0
2. Launch app with no device connected
3. Click Save Logs button

<img width="474" alt="Screen Shot 2019-06-18 at 11 56 24 AM" src="https://user-images.githubusercontent.com/2849403/59700006-8b665a80-91c0-11e9-82df-bd5c0dda26a9.png">

**Comment by Andychochocho** [comment]
I disabled click functionality when device is not connected. Implemented in 76b2610
